export const SET_CURRNETMUSIC = 'SET_CURRENTMUSIC'
export const SET_CURRNETMUSIC_OBJECT = 'SET_CURRNETMUSIC_OBJECT'
export const REMOVE_INDEX = 'REMOVE_INDEX'
export const SET_CURRENTMUSIC_INIT = 'SET_CURRENTMUSIC_INIT'
